synnada-ai/mithril

- .github/label_to_devs.yml
- .github/labeler.yml
- releases/changelog/0.1.1.md
This PR tries/exercises release and commit message automations.
Added a directory for storing changelogs.
> chore: Add changelog for version 0.1.1

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/create-an-epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other-issues.md
Closes #22.
Updates issue templates to reduce cruft.
> style: Clean-up issue/PR templates to make them more concise

- mithril/framework/constraints.py
- tests/scripts/test_constraints.py
Reduce constraint symbolic shape inference bug fixed. Closes #31 
-  Reduce constraint updated.
- Tests for the bug added.
> fix: Fix reduce constraint bug

- examples/flux/auto_encoder.py
- examples/flux/layers.py
closes #41.
- Add some submodules of the Flux
> chore: Add some submodules of flux

- examples/flux/layers.py
Closes #95 
- FLUX layers added
> chore: Add FLUX layers

- examples/flux/layers.py
EmbedND implementation fro onboarding. Related to #95, and #96.
rotary position embedding and embedND were implemented
> feat: Add EmbedND model for Flux

- mithril/backends/with_autograd/jax_backend/ops.py
- mithril/backends/with_autograd/mlx_backend/ops.py
- mithril/backends/with_autograd/torch_backend/ops.py
- mithril/backends/with_manualgrad/numpy_backend/ops.py
- mithril/backends/with_manualgrad/numpy_backend/ops_grad.py
- mithril/models/primitives.py
- tests/scripts/test_all_models.py
- tests/scripts/test_shapes.py
Closes #97 
- Zeros like primitive is added.
> feat: Add zeros like primitive

- mithril/framework/common.py
- mithril/framework/logical/model.py
- tests/scripts/test_extend_template.py
Closes #103 .
-  Added item method to extend template.
> feat: Add item method to Extend Template

- examples/gpt/model.py
- examples/gpt/run_sample.py
> refactor: Refactor gpt

- examples/flux/auto_encoder.py
- mithril/models/primitives.py
Closes #112 
-  Added auto encoder models for flux
> chore: Add Flux auto encoder model

- mithril/backends/with_autograd/jax_backend/ops.py
- mithril/backends/with_autograd/mlx_backend/ops.py
- mithril/backends/with_autograd/torch_backend/ops.py
- mithril/backends/with_manualgrad/numpy_backend/ops.py
- mithril/framework/logical/base.py
- mithril/framework/logical/primitive.py
- mithril/framework/physical/data_store.py
- mithril/framework/physical/flat_graph.py
- mithril/framework/physical/model.py
- mithril/models/primitives.py
- tests/scripts/test_all_models.py
- tests/scripts/test_pm.py
Closes #123 
- Random seed values added to datastore.
- FlatGraph keep track of random seed keys.
- PM updates seed values in every evaluation.
> feat: Seed key for rand primitive

- mithril/backends/with_autograd/jax_backend/ops.py
- mithril/backends/with_autograd/mlx_backend/ops.py
- mithril/backends/with_autograd/torch_backend/ops.py
- mithril/backends/with_manualgrad/numpy_backend/ops.py
- mithril/framework/logical/essential_primitives.py
- tests/scripts/test_all_models.py
Closes #152 
- Minimum and maximum primitives added with their tests.
> feat: Add support for minimum and maximum primitives

- mithril/framework/codegen/numpy_gen.py
- mithril/framework/codegen/python_gen.py
- tests/scripts/test_codegen.py
- tests/scripts/test_functions.py
Cache static values inline to make generated code shorter.
Closes #158
> feat: cache static values inline

- mithril/framework/physical/flat_graph.py
- mithril/framework/physical/model.py
- tests/scripts/test_flat_graph.py
- tests/scripts/test_functions.py
- tests/scripts/test_io_key.py
- tests/scripts/test_scripts.py
- tests/scripts/test_utils.py
This PR simplifies the internal graph representation in Mithril's flat graph implementation. We've removed the unnecessary Node class and streamlined the graph representation using just GConnection objects, which makes the code more maintainable and efficient. Closes #224.
- Removed the Node class, simplifying the graph structure hierarchy
- Modified GConnection to directly reference operators instead of through nodes
- Streamlined graph traversal and management methods
- Improved efficiency of node removal and graph pruning operations
- Updated property access methods for more direct model access
Benefits
- More maintainable and less complex graph representation
- Simplified debugging and issue tracing
- Better performance for large graph operations
> refactor:  Refactor FlatGraph

- mithril/cores/python/jax/ops.py
- mithril/cores/python/mlx/ops.py
- mithril/cores/python/numpy/ops.py
- mithril/cores/python/torch/ops.py
- mithril/models/primitives.py
- tests/scripts/test_all_models.py
Include a brief and concise description of the PR. 
Closes #237.
* RandInt Primitive added.
* Corresponding backend ops functions added.
> feat: Add RandInt Primitive Model

- .github/contributors.yml
- .github/labeler.yml
- .github/workflows/ci-test-macos.yaml
Closes #258.
- CI-test script is changed for integrating self-hosted runner into CI for MacOs.
> chore: self-hosted macOS runner is integrated into mithril

- .github/workflows/add-to-project.yml
- .github/workflows/auto-move-issue-done.yml
- .github/workflows/auto-move-pr.yml
- .github/workflows/auto-move.yml
- examples/flux/clip.py
- examples/flux/t5.py
Closes #270 
- Added GitHub actions for automated track of issues and PR's on Projects/Kanban.
> chore: Create automation for Projects.

- .github/setting_self_hosted_macos_runners.md
- .github/workflows/ci-test-macos.yaml
Closes #267.
- MacOS self-hosted workflow script is reactivated
> chore: self-hosted runner is reactivated

- examples/flux/layers.py
- mithril/framework/logical/base.py
- mithril/framework/logical/model.py
- tests/scripts/test_immediate_extend.py
Closes #382, #384
Minor bugs are fixed in Provisional logic.
- Exposing already existing internal connection as an output
- Merge Constraint solvers in provisional models with main model
> fix: Minor bugs in Provisional Logic

- mithril/framework/physical/model.py
- tests/scripts/test_automized_shardings.py
- tests/scripts/test_examples.py
- tests/scripts/test_propose_shardings.py
Closes #380
A new method called `propose_shardings` added
> feat: Introduce Propose Sharding Logic

- mithril/framework/common.py
- setup.py
- tests/scripts/test_differentiable.py
Closes #282.
- set_type method of Tensor updates differantiable.
> fix: Update differentiable of Tensor in set_type
